name: CI

on:
  push:
    branches:
      - "main"

jobs:
  build:
    name: Build
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set XCode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "26.2"

      - name: Install xcbeautify
        run: brew install xcbeautify

      - name: Build
        run: |
          xcodebuild \
            CODE_SIGN_IDENTITY='' \
            CODE_SIGN_STYLE='Automatic' \
            -scheme EightQueens \
            -destination 'platform=macOS,arch=arm64' \
            -workspace EightQueens.xcodeproj/project.xcworkspace \
            clean build analyze | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
