name: CI

on:
  push:
    branches:
      - "main"

jobs:
  build:
    name: Build
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install xcbeautify
        run: brew install xcbeautify

      - name: Build
        run: |
          xcodebuild \
            -scheme EightQueens \
            -destination 'platform=macOS,arch=arm64' \
            -workspace EightQueens.xcodeproj/project.xcworkspace \
            clean build analyze | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
